### ISSUE TITLE
AutoGrid is trying to find MeshLibrary 

### ISSUE THREAD

**Issue by arturertel** [XLIVE99/Gridmap_Autotile#1]
![Unbenannt](https://user-images.githubusercontent.com/11181906/123521402-ac6abb80-d6b6-11eb-9524-a9fcae63c3ed.png)
Hello, thanks for the recommendation to select another node so that AutoGrid checks the gridmap again. Unfortunately this did not help. Here is a screenshot and a video which hopefully helps to understand where the error is. I would be very happy if this error is fixed soon. Thanks for this addon!

https://youtu.be/-B5fS3PHVUo

**Comment by XLIVE99** [comment]
It seems you are painting bitmask wrong.
![Correct Painting](https://user-images.githubusercontent.com/30470295/123523258-3a50a180-d6cb-11eb-95a2-45cd0f3902c2.png)
You need to paint them as shown in the image above. My view is from top. If I wasn't clear enough, I can upload a small video how to paint correctly in your situation.
I will update the plugin to fix some bugs soon.

**Comment by arturertel** [comment]
hey thanks for the quick reply!
i think i was too much in 2D with my thinking :D 

You can use this video for your purposes if you like.
I'm looking forward to your updates too!

https://user-images.githubusercontent.com/11181906/123525439-eb0d6f80-d6d0-11eb-883b-5b6bd5e46b68.mp4
