### ISSUE TITLE
Video walkthrough?

### ISSUE THREAD

**Issue by programnoir** [XLIVE99/Gridmap_Autotile#4]
Hey there -- terribly sorry to ask this. I attempted to follow the instructions that are shown in the FAQ and PDF, but I had some trouble with completing setup after spending a long time setting up bitmasks. I'm a bit lost with the actual "output" of the autotile setup and how to use it in a meshlibrary.

I know this isn't a tech support forum, and this isn't actually a feature request, but would you be willing to make a quick video showing how you use the plugin from start to finish? It would help clear up the confusion I'm having with using the plugin. I am making sure this is being used in Godot 3.5, at least, if part's correct.

**Comment by programnoir** [comment]
Ah, okay! Sorry again, I actually managed to figure it out on the second try.

1. Create your tiles. I did mine in Blender, one object per tile.
2. Import your tile 3D resources into Godot. Don't activate the plugin yet.
3. Create a new inherited scene from the .glb file you generate, if you used Blender.
4. This creates a Node3D parent with a bunch of MeshInstances. I made about 47 since I was making 3x3 minimal tiles.
5. Go through each of the MeshInstance nodes, make sure the materials are working how you want, add collision boxes, etc.
6. Okay, activate the plugin now. A new tab "AutoGrid" appears next to the Inspector tab.
7. Turn Autotile on, turn Edit mode on.
8. Select your first MeshInstance node. While selected, a new dropdown menu should appear in the 3D editor named AutoGrid, next to the Mesh dropdown menu. If it appears for a moment and disappears, it's a weird bug, you'll need to start over. Sorry! I should probably make an actual bug report for this.
9. Select "create bitmask" from the dropdown menu.
10. How you handle your bitmasks depends on what you want your autotile to do. I am assuming most people just want to autotile the ground, so select "Only Y" from the dropdown menu to make life a little easier.
- - Note: In Godot 4.x, this was renamed to "X & Z Axises")
11. While the MeshInstance is selected, click the cube to enable the tile's bit. Red cubes indicate what neighboring tiles need to be present for the currently visible tile to look how it does.
12. You'll manually go through all of these tiles and repeat the same steps.
13. When you are done setting all the bitmasks, select the root Node3D node.
14. Return to the AutoGrid tab next to the Inspector tab. Save the scene if you haven't already.
15. If you're just trying to autotile the ground, configure the settings to be Autotile Mode as 3x3 Minimal, Autotile Axis to All, and Autotile Scan Axis to Only Y. These settings worked okay for me but the dev here might make minor corrections here lol
- - Note: In Godot 4.x, "Scan Axis" is renamed to "Autotile Axis" and the option is "X & Z Axises". You also want Tile Normal Axis to be set to "Y Axis"
16. Press "Create Autotile Info". Save the file in the same folder as your inherited scene. This also creates a new MeshInstance 
node that represents your autogrid.
17. Save your scene, then go to Scene menu -> Convert to -> MeshLibrary.
- - In Godot 4.x, "Convert to" was renamed to "Export as..."
18. This will save a MeshLibrary resource.
19. Create a Gridmap node and load your MeshLibrary into it. Select the last tile in the MeshLibrary.
20. In the AutoGrid tab, make sure the AutoGrid's Autotile option is enabled.
21. You should now be able to draw the ground accordingly.

![image](https://github.com/XLIVE99/AutoGrid/assets/1452074/d277be8f-18e4-4cdf-95f7-9e1dc4ce97fd)

**Comment by XLIVE99** [comment]
Thank you for using the AutoGrid. I didn't know the documentation is not that helpful, thank you for your feedback. I will record a video for it. Also I heard this plugin doesn't work in 4.x versions, I will update the plugin in my free time.
